<?xml version="1.0" encoding="utf-8"?><Database Name="TREOB_ULTIMATE" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.1.78;Initial Catalog=TREOB_ULTIMATE;Persist Security Info=True;User ID=kokluce" SettingsObjectName="HIZMET.Properties.Settings" SettingsPropertyName="TREOB_ULTIMATEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.PERSONEL" Member="PERSONELs">
    <Type Name="PERSONEL">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SICIL_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KIMLIK_SERI_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TC_NO" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
      <Column Name="ADI_SOYADI" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ANNE_ADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BABA_ADI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOGUM_YERI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOGUM_TARIHI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MEDENI_DURUM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUFUS_KAYDI_IL" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NUFUS_KAYDI_ILCE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAHALLE_KOY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="KUTUK_CILT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="HANE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SAYFA_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TEL_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EV_ADRESI" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="FIRMA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIRIS_TARIHI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CIKIS_TARIHI" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CALISMA_DURUMU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="L_DEPARTMAN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="L_GOREV_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DURUM" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RESIM" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="KART_NO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>