#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HIZMET
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TREOB_ULTIMATE")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertPERSONEL(PERSONEL instance);
    partial void UpdatePERSONEL(PERSONEL instance);
    partial void DeletePERSONEL(PERSONEL instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HIZMET.Properties.Settings.Default.TREOB_ULTIMATEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<PERSONEL> PERSONELs
		{
			get
			{
				return this.GetTable<PERSONEL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PERSONEL")]
	public partial class PERSONEL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SICIL_NO;
		
		private string _KIMLIK_SERI_NO;
		
		private string _TC_NO;
		
		private string _ADI_SOYADI;
		
		private string _ANNE_ADI;
		
		private string _BABA_ADI;
		
		private string _DOGUM_YERI;
		
		private System.Nullable<System.DateTime> _DOGUM_TARIHI;
		
		private string _MEDENI_DURUM;
		
		private string _NUFUS_KAYDI_IL;
		
		private string _NUFUS_KAYDI_ILCE;
		
		private string _MAHALLE_KOY;
		
		private string _KUTUK_CILT;
		
		private string _HANE;
		
		private string _SAYFA_NO;
		
		private string _TEL_NO;
		
		private string _EV_ADRESI;
		
		private string _FIRMA;
		
		private System.Nullable<System.DateTime> _GIRIS_TARIHI;
		
		private System.Nullable<System.DateTime> _CIKIS_TARIHI;
		
		private string _CALISMA_DURUMU;
		
		private System.Nullable<int> _L_DEPARTMAN_ID;
		
		private System.Nullable<int> _L_GOREV_ID;
		
		private bool _DURUM;
		
		private string _RESIM;
		
		private string _EMAIL;
		
		private string _KART_NO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSICIL_NOChanging(string value);
    partial void OnSICIL_NOChanged();
    partial void OnKIMLIK_SERI_NOChanging(string value);
    partial void OnKIMLIK_SERI_NOChanged();
    partial void OnTC_NOChanging(string value);
    partial void OnTC_NOChanged();
    partial void OnADI_SOYADIChanging(string value);
    partial void OnADI_SOYADIChanged();
    partial void OnANNE_ADIChanging(string value);
    partial void OnANNE_ADIChanged();
    partial void OnBABA_ADIChanging(string value);
    partial void OnBABA_ADIChanged();
    partial void OnDOGUM_YERIChanging(string value);
    partial void OnDOGUM_YERIChanged();
    partial void OnDOGUM_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnDOGUM_TARIHIChanged();
    partial void OnMEDENI_DURUMChanging(string value);
    partial void OnMEDENI_DURUMChanged();
    partial void OnNUFUS_KAYDI_ILChanging(string value);
    partial void OnNUFUS_KAYDI_ILChanged();
    partial void OnNUFUS_KAYDI_ILCEChanging(string value);
    partial void OnNUFUS_KAYDI_ILCEChanged();
    partial void OnMAHALLE_KOYChanging(string value);
    partial void OnMAHALLE_KOYChanged();
    partial void OnKUTUK_CILTChanging(string value);
    partial void OnKUTUK_CILTChanged();
    partial void OnHANEChanging(string value);
    partial void OnHANEChanged();
    partial void OnSAYFA_NOChanging(string value);
    partial void OnSAYFA_NOChanged();
    partial void OnTEL_NOChanging(string value);
    partial void OnTEL_NOChanged();
    partial void OnEV_ADRESIChanging(string value);
    partial void OnEV_ADRESIChanged();
    partial void OnFIRMAChanging(string value);
    partial void OnFIRMAChanged();
    partial void OnGIRIS_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnGIRIS_TARIHIChanged();
    partial void OnCIKIS_TARIHIChanging(System.Nullable<System.DateTime> value);
    partial void OnCIKIS_TARIHIChanged();
    partial void OnCALISMA_DURUMUChanging(string value);
    partial void OnCALISMA_DURUMUChanged();
    partial void OnL_DEPARTMAN_IDChanging(System.Nullable<int> value);
    partial void OnL_DEPARTMAN_IDChanged();
    partial void OnL_GOREV_IDChanging(System.Nullable<int> value);
    partial void OnL_GOREV_IDChanged();
    partial void OnDURUMChanging(bool value);
    partial void OnDURUMChanged();
    partial void OnRESIMChanging(string value);
    partial void OnRESIMChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnKART_NOChanging(string value);
    partial void OnKART_NOChanged();
    #endregion
		
		public PERSONEL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SICIL_NO", DbType="NVarChar(50)")]
		public string SICIL_NO
		{
			get
			{
				return this._SICIL_NO;
			}
			set
			{
				if ((this._SICIL_NO != value))
				{
					this.OnSICIL_NOChanging(value);
					this.SendPropertyChanging();
					this._SICIL_NO = value;
					this.SendPropertyChanged("SICIL_NO");
					this.OnSICIL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KIMLIK_SERI_NO", DbType="NVarChar(50)")]
		public string KIMLIK_SERI_NO
		{
			get
			{
				return this._KIMLIK_SERI_NO;
			}
			set
			{
				if ((this._KIMLIK_SERI_NO != value))
				{
					this.OnKIMLIK_SERI_NOChanging(value);
					this.SendPropertyChanging();
					this._KIMLIK_SERI_NO = value;
					this.SendPropertyChanged("KIMLIK_SERI_NO");
					this.OnKIMLIK_SERI_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC_NO", DbType="NVarChar(11)")]
		public string TC_NO
		{
			get
			{
				return this._TC_NO;
			}
			set
			{
				if ((this._TC_NO != value))
				{
					this.OnTC_NOChanging(value);
					this.SendPropertyChanging();
					this._TC_NO = value;
					this.SendPropertyChanged("TC_NO");
					this.OnTC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADI_SOYADI", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ADI_SOYADI
		{
			get
			{
				return this._ADI_SOYADI;
			}
			set
			{
				if ((this._ADI_SOYADI != value))
				{
					this.OnADI_SOYADIChanging(value);
					this.SendPropertyChanging();
					this._ADI_SOYADI = value;
					this.SendPropertyChanged("ADI_SOYADI");
					this.OnADI_SOYADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ANNE_ADI", DbType="NVarChar(50)")]
		public string ANNE_ADI
		{
			get
			{
				return this._ANNE_ADI;
			}
			set
			{
				if ((this._ANNE_ADI != value))
				{
					this.OnANNE_ADIChanging(value);
					this.SendPropertyChanging();
					this._ANNE_ADI = value;
					this.SendPropertyChanged("ANNE_ADI");
					this.OnANNE_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BABA_ADI", DbType="NVarChar(50)")]
		public string BABA_ADI
		{
			get
			{
				return this._BABA_ADI;
			}
			set
			{
				if ((this._BABA_ADI != value))
				{
					this.OnBABA_ADIChanging(value);
					this.SendPropertyChanging();
					this._BABA_ADI = value;
					this.SendPropertyChanged("BABA_ADI");
					this.OnBABA_ADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOGUM_YERI", DbType="NVarChar(50)")]
		public string DOGUM_YERI
		{
			get
			{
				return this._DOGUM_YERI;
			}
			set
			{
				if ((this._DOGUM_YERI != value))
				{
					this.OnDOGUM_YERIChanging(value);
					this.SendPropertyChanging();
					this._DOGUM_YERI = value;
					this.SendPropertyChanged("DOGUM_YERI");
					this.OnDOGUM_YERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOGUM_TARIHI", DbType="Date")]
		public System.Nullable<System.DateTime> DOGUM_TARIHI
		{
			get
			{
				return this._DOGUM_TARIHI;
			}
			set
			{
				if ((this._DOGUM_TARIHI != value))
				{
					this.OnDOGUM_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._DOGUM_TARIHI = value;
					this.SendPropertyChanged("DOGUM_TARIHI");
					this.OnDOGUM_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDENI_DURUM", DbType="NVarChar(50)")]
		public string MEDENI_DURUM
		{
			get
			{
				return this._MEDENI_DURUM;
			}
			set
			{
				if ((this._MEDENI_DURUM != value))
				{
					this.OnMEDENI_DURUMChanging(value);
					this.SendPropertyChanging();
					this._MEDENI_DURUM = value;
					this.SendPropertyChanged("MEDENI_DURUM");
					this.OnMEDENI_DURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUFUS_KAYDI_IL", DbType="NVarChar(50)")]
		public string NUFUS_KAYDI_IL
		{
			get
			{
				return this._NUFUS_KAYDI_IL;
			}
			set
			{
				if ((this._NUFUS_KAYDI_IL != value))
				{
					this.OnNUFUS_KAYDI_ILChanging(value);
					this.SendPropertyChanging();
					this._NUFUS_KAYDI_IL = value;
					this.SendPropertyChanged("NUFUS_KAYDI_IL");
					this.OnNUFUS_KAYDI_ILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUFUS_KAYDI_ILCE", DbType="NVarChar(50)")]
		public string NUFUS_KAYDI_ILCE
		{
			get
			{
				return this._NUFUS_KAYDI_ILCE;
			}
			set
			{
				if ((this._NUFUS_KAYDI_ILCE != value))
				{
					this.OnNUFUS_KAYDI_ILCEChanging(value);
					this.SendPropertyChanging();
					this._NUFUS_KAYDI_ILCE = value;
					this.SendPropertyChanged("NUFUS_KAYDI_ILCE");
					this.OnNUFUS_KAYDI_ILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAHALLE_KOY", DbType="NVarChar(100)")]
		public string MAHALLE_KOY
		{
			get
			{
				return this._MAHALLE_KOY;
			}
			set
			{
				if ((this._MAHALLE_KOY != value))
				{
					this.OnMAHALLE_KOYChanging(value);
					this.SendPropertyChanging();
					this._MAHALLE_KOY = value;
					this.SendPropertyChanged("MAHALLE_KOY");
					this.OnMAHALLE_KOYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KUTUK_CILT", DbType="NVarChar(50)")]
		public string KUTUK_CILT
		{
			get
			{
				return this._KUTUK_CILT;
			}
			set
			{
				if ((this._KUTUK_CILT != value))
				{
					this.OnKUTUK_CILTChanging(value);
					this.SendPropertyChanging();
					this._KUTUK_CILT = value;
					this.SendPropertyChanged("KUTUK_CILT");
					this.OnKUTUK_CILTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HANE", DbType="NVarChar(50)")]
		public string HANE
		{
			get
			{
				return this._HANE;
			}
			set
			{
				if ((this._HANE != value))
				{
					this.OnHANEChanging(value);
					this.SendPropertyChanging();
					this._HANE = value;
					this.SendPropertyChanged("HANE");
					this.OnHANEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAYFA_NO", DbType="NVarChar(50)")]
		public string SAYFA_NO
		{
			get
			{
				return this._SAYFA_NO;
			}
			set
			{
				if ((this._SAYFA_NO != value))
				{
					this.OnSAYFA_NOChanging(value);
					this.SendPropertyChanging();
					this._SAYFA_NO = value;
					this.SendPropertyChanged("SAYFA_NO");
					this.OnSAYFA_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEL_NO", DbType="NVarChar(50)")]
		public string TEL_NO
		{
			get
			{
				return this._TEL_NO;
			}
			set
			{
				if ((this._TEL_NO != value))
				{
					this.OnTEL_NOChanging(value);
					this.SendPropertyChanging();
					this._TEL_NO = value;
					this.SendPropertyChanged("TEL_NO");
					this.OnTEL_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EV_ADRESI", DbType="NVarChar(150)")]
		public string EV_ADRESI
		{
			get
			{
				return this._EV_ADRESI;
			}
			set
			{
				if ((this._EV_ADRESI != value))
				{
					this.OnEV_ADRESIChanging(value);
					this.SendPropertyChanging();
					this._EV_ADRESI = value;
					this.SendPropertyChanged("EV_ADRESI");
					this.OnEV_ADRESIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMA", DbType="NVarChar(50)")]
		public string FIRMA
		{
			get
			{
				return this._FIRMA;
			}
			set
			{
				if ((this._FIRMA != value))
				{
					this.OnFIRMAChanging(value);
					this.SendPropertyChanging();
					this._FIRMA = value;
					this.SendPropertyChanged("FIRMA");
					this.OnFIRMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIRIS_TARIHI", DbType="Date")]
		public System.Nullable<System.DateTime> GIRIS_TARIHI
		{
			get
			{
				return this._GIRIS_TARIHI;
			}
			set
			{
				if ((this._GIRIS_TARIHI != value))
				{
					this.OnGIRIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._GIRIS_TARIHI = value;
					this.SendPropertyChanged("GIRIS_TARIHI");
					this.OnGIRIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIKIS_TARIHI", DbType="Date")]
		public System.Nullable<System.DateTime> CIKIS_TARIHI
		{
			get
			{
				return this._CIKIS_TARIHI;
			}
			set
			{
				if ((this._CIKIS_TARIHI != value))
				{
					this.OnCIKIS_TARIHIChanging(value);
					this.SendPropertyChanging();
					this._CIKIS_TARIHI = value;
					this.SendPropertyChanged("CIKIS_TARIHI");
					this.OnCIKIS_TARIHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CALISMA_DURUMU", DbType="NVarChar(50)")]
		public string CALISMA_DURUMU
		{
			get
			{
				return this._CALISMA_DURUMU;
			}
			set
			{
				if ((this._CALISMA_DURUMU != value))
				{
					this.OnCALISMA_DURUMUChanging(value);
					this.SendPropertyChanging();
					this._CALISMA_DURUMU = value;
					this.SendPropertyChanged("CALISMA_DURUMU");
					this.OnCALISMA_DURUMUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_DEPARTMAN_ID", DbType="Int")]
		public System.Nullable<int> L_DEPARTMAN_ID
		{
			get
			{
				return this._L_DEPARTMAN_ID;
			}
			set
			{
				if ((this._L_DEPARTMAN_ID != value))
				{
					this.OnL_DEPARTMAN_IDChanging(value);
					this.SendPropertyChanging();
					this._L_DEPARTMAN_ID = value;
					this.SendPropertyChanged("L_DEPARTMAN_ID");
					this.OnL_DEPARTMAN_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L_GOREV_ID", DbType="Int")]
		public System.Nullable<int> L_GOREV_ID
		{
			get
			{
				return this._L_GOREV_ID;
			}
			set
			{
				if ((this._L_GOREV_ID != value))
				{
					this.OnL_GOREV_IDChanging(value);
					this.SendPropertyChanging();
					this._L_GOREV_ID = value;
					this.SendPropertyChanged("L_GOREV_ID");
					this.OnL_GOREV_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DURUM", DbType="Bit NOT NULL")]
		public bool DURUM
		{
			get
			{
				return this._DURUM;
			}
			set
			{
				if ((this._DURUM != value))
				{
					this.OnDURUMChanging(value);
					this.SendPropertyChanging();
					this._DURUM = value;
					this.SendPropertyChanged("DURUM");
					this.OnDURUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESIM", DbType="NVarChar(250)")]
		public string RESIM
		{
			get
			{
				return this._RESIM;
			}
			set
			{
				if ((this._RESIM != value))
				{
					this.OnRESIMChanging(value);
					this.SendPropertyChanging();
					this._RESIM = value;
					this.SendPropertyChanged("RESIM");
					this.OnRESIMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="NVarChar(300)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KART_NO", DbType="NVarChar(50)")]
		public string KART_NO
		{
			get
			{
				return this._KART_NO;
			}
			set
			{
				if ((this._KART_NO != value))
				{
					this.OnKART_NOChanging(value);
					this.SendPropertyChanging();
					this._KART_NO = value;
					this.SendPropertyChanged("KART_NO");
					this.OnKART_NOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
